In [2]:
import pandas as pd

In [6]:
# Financial Ratios: Firm Level is a powerful engine that delivers over 70 pre-calculated financial ratios for all U.S. companies across eight different categories (valuation, liquidity, profitability, financial soundness, etc.). Researchers can easily obtain individual ratios for all firms in North America through point-and-click on the web query. This product can be used as a convenient tool to obtain various ratios as characteristics for controls in empirical research.
raw = pd.read_csv("./Archive(1)/wrds_quarterly_ratios.csv")
raw.head(4)

,gvkey,permno,adate,qdate,public_date,CAPEI,bm,evm,pe_op_basic,pe_op_dil,...,sale_nwc,rd_sale,adv_sale,staff_sale,accrual,ptb,PEG_trailing,divyield,TICKER,cusip
0,1004,54594,2009-05-31,2009-11-30,2010-01-31,17.934,1.077,7.981,14.758,15.243,...,2.257,0.0,0.0,0.0,-0.043,1.152,2.250,NaN,AIR,00036110
1,1004,54594,2009-05-31,2009-11-30,2010-02-28,17.554,1.077,7.981,14.446,14.921,...,2.257,0.0,0.0,0.0,-0.043,1.128,2.203,NaN,AIR,00036110
2,1004,54594,2009-05-31,2009-11-30,2010-03-31,19.257,1.077,7.981,15.809,16.329,...,2.257,0.0,0.0,0.0,-0.043,1.237,2.410,NaN,AIR,00036110
3,1004,54594,2009-05-31,2010-02-28,2010-04-30,18.304,0.898,9.293,16.146,16.473,...,2.176,0.0,0.0,0.0,-0.087,1.197,31.895,NaN,AIR,00036110

In [15]:
raw.columns.values

array(['gvkey', 'permno', 'adate', 'qdate', 'public_date', 'CAPEI', 'bm',
       'evm', 'pe_op_basic', 'pe_op_dil', 'pe_exi', 'pe_inc', 'ps', 'pcf',
       'dpr', 'npm', 'opmbd', 'opmad', 'gpm', 'ptpm', 'cfm', 'roa', 'roe',
       'roce', 'efftax', 'aftret_eq', 'aftret_invcapx', 'aftret_equity',
       'pretret_noa', 'pretret_earnat', 'GProf', 'equity_invcap',
       'debt_invcap', 'totdebt_invcap', 'capital_ratio', 'int_debt',
       'int_totdebt', 'cash_lt', 'invt_act', 'rect_act', 'debt_at',
       'debt_ebitda', 'short_debt', 'curr_debt', 'lt_debt', 'profit_lct',
       'ocf_lct', 'cash_debt', 'fcf_ocf', 'lt_ppent', 'dltt_be',
       'debt_assets', 'debt_capital', 'de_ratio', 'intcov',
       'intcov_ratio', 'cash_ratio', 'quick_ratio', 'curr_ratio',
       'cash_conversion', 'inv_turn', 'at_turn', 'rect_turn', 'pay_turn',
       'sale_invcap', 'sale_equity', 'sale_nwc', 'rd_sale', 'adv_sale',
       'staff_sale', 'accrual', 'ptb', 'PEG_trailing', 'divyield',
       'TICKER', 'cusip'], dtype=object)

In [5]:
compu = pd.read_csv("./Archive(1)/compustat_quarterly.csv")
compu.head(1)

,gvkey,datadate,fyearq,fqtr,fyr,indfmt,consol,popsrc,datafmt,tic,...,xoptepsp12,xoptepsq,xoptepsqp,xoptq,xoptqp,xrdq,xsgaq,costat,dvpspq,adjex
0,1004,2010-02-28,2009,3.0,5,INDL,C,D,STD,AIR,...,0.0,0.0,0.0,0.0,0.0,NaN,34.091,A,0.0,1.0

In [14]:
print(compu.columns.values)

['gvkey' 'datadate' 'fyearq' 'fqtr' 'fyr' 'indfmt' 'consol' 'popsrc'
 'datafmt' 'tic' 'cusip' 'curcdq' 'datacqtr' 'datafqtr' 'acchgq'
 'acomincq' 'acoq' 'actq' 'altoq' 'ancq' 'anoq' 'aociderglq' 'aociotherq'
 'aocipenq' 'aocisecglq' 'aol2q' 'aoq' 'apq' 'aqaq' 'aqdq' 'aqepsq'
 'aqpl1q' 'aqpq' 'arcedq' 'arceepsq' 'arceq' 'atq' 'aul3q' 'billexceq'
 'capr1q' 'capr2q' 'capr3q' 'capsftq' 'capsq' 'ceiexbillq' 'ceqq' 'cheq'
 'chq' 'cibegniq' 'cicurrq' 'ciderglq' 'cimiiq' 'ciotherq' 'cipenq' 'ciq'
 'cisecglq' 'citotalq' 'cogsq' 'csh12q' 'cshfd12' 'cshfdq' 'cshiq'
 'cshopq' 'cshoq' 'cshprq' 'cstkcvq' 'cstkeq' 'cstkq' 'dcomq' 'dd1q'
 'deracq' 'deraltq' 'derhedglq' 'derlcq' 'derlltq' 'diladq' 'dilavq'
 'dlcq' 'dlttq' 'doq' 'dpacreq' 'dpactq' 'dpq' 'dpretq' 'drcq' 'drltq'
 'dteaq' 'dtedq' 'dteepsq' 'dtepq' 'dvintfq' 'dvpq' 'epsf12' 'epsfi12'
 'epsfiq' 'epsfxq' 'epspi12' 'epspiq' 'epspxq' 'epsx12' 'esopctq'
 'esopnrq' 'esoprq' 'esoptq' 'esubq' 'fcaq' 'ffoq' 'finacoq' 'finaoq'
 'finchq' 'findlcq' 'findltq' 'finivstq' 'finlcoq' 'finltoq' 'finnpq'
 'finreccq' 'finrecltq' 'finrevq' 'finxintq' 'finxoprq' 'gdwlamq'
 'gdwlia12' 'gdwliaq' 'gdwlid12' 'gdwlidq' 'gdwlieps12' 'gdwliepsq'
 'gdwlipq' 'gdwlq' 'glaq' 'glcea12' 'glceaq' 'glced12' 'glcedq'
 'glceeps12' 'glceepsq' 'glcepq' 'gldq' 'glepsq' 'glivq' 'glpq' 'hedgeglq'
 'ibadj12' 'ibadjq' 'ibcomq' 'ibmiiq' 'ibq' 'icaptq' 'intaccq' 'intanoq'
 'intanq' 'invfgq' 'invoq' 'invrmq' 'invtq' 'invwipq' 'ivaeqq' 'ivaoq'
 'ivltq' 'ivstq' 'lcoq' 'lctq' 'lltq' 'lnoq' 'lol2q' 'loq' 'loxdrq'
 'lqpl1q' 'lseq' 'ltmibq' 'ltq' 'lul3q' 'mibnq' 'mibq' 'mibtq' 'miiq'
 'msaq' 'ncoq' 'niitq' 'nimq' 'niq' 'nopiq' 'npatq' 'npq' 'nrtxtdq'
 'nrtxtepsq' 'nrtxtq' 'obkq' 'oepf12' 'oeps12' 'oepsxq' 'oiadpq' 'oibdpq'
 'opepsq' 'optdrq' 'optfvgrq' 'optlifeq' 'optrfrq' 'optvolq' 'piq' 'pllq'
 'pnc12' 'pncd12' 'pncdq' 'pnceps12' 'pncepsq' 'pnciapq' 'pnciaq'
 'pncidpq' 'pncidq' 'pnciepspq' 'pnciepsq' 'pncippq' 'pncipq' 'pncpd12'
 'pncpdq' 'pncpeps12' 'pncpepsq' 'pncpq' 'pncq' 'pncwiapq' 'pncwiaq'
 'pncwidpq' 'pncwidq' 'pncwiepq' 'pncwiepsq' 'pncwippq' 'pncwipq'
 'pnrshoq' 'ppegtq' 'ppentq' 'prcaq' 'prcd12' 'prcdq' 'prce12' 'prceps12'
 'prcepsq' 'prcpd12' 'prcpdq' 'prcpeps12' 'prcpepsq' 'prcpq' 'prcraq'
 'prshoq' 'pstknq' 'pstkq' 'pstkrq' 'rcaq' 'rcdq' 'rcepsq' 'rcpq' 'rdipaq'
 'rdipdq' 'rdipepsq' 'rdipq' 'recdq' 'rectaq' 'rectoq' 'rectq' 'rectrq'
 'recubq' 'req' 'retq' 'reunaq' 'revtq' 'rllq' 'rra12' 'rraq' 'rrd12'
 'rrdq' 'rreps12' 'rrepsq' 'rrpq' 'rstcheltq' 'rstcheq' 'saleq' 'seqoq'
 'seqq' 'seta12' 'setaq' 'setd12' 'setdq' 'seteps12' 'setepsq' 'setpq'
 'spce12' 'spced12' 'spcedpq' 'spcedq' 'spceeps12' 'spceepsp12'
 'spceepspq' 'spceepsq' 'spcep12' 'spcepd12' 'spcepq' 'spceq' 'spidq'
 'spiepsq' 'spioaq' 'spiopq' 'spiq' 'sretq' 'stkcoq' 'stkcpaq' 'teqq'
 'tfvaq' 'tfvceq' 'tfvlq' 'tieq' 'tiiq' 'tstknq' 'tstkq' 'txdbaq'
 'txdbcaq' 'txdbclq' 'txdbq' 'txdiq' 'txditcq' 'txpq' 'txtq' 'txwq'
 'uacoq' 'uaoq' 'uaptq' 'ucapsq' 'ucconsq' 'uceqq' 'uddq' 'udmbq' 'udoltq'
 'udpcoq' 'udvpq' 'ugiq' 'uinvq' 'ulcoq' 'uniamiq' 'unopincq' 'uopiq'
 'updvpq' 'upmcstkq' 'upmpfq' 'upmpfsq' 'upmsubpq' 'upstkcq' 'upstkq'
 'urectq' 'uspiq' 'usubdvpq' 'usubpcvq' 'utemq' 'wcapq' 'wdaq' 'wddq'
 'wdepsq' 'wdpq' 'xaccq' 'xidoq' 'xintq' 'xiq' 'xoprq' 'xopt12' 'xoptd12'
 'xoptd12p' 'xoptdq' 'xoptdqp' 'xopteps12' 'xoptepsp12' 'xoptepsq'
 'xoptepsqp' 'xoptq' 'xoptqp' 'xrdq' 'xsgaq' 'costat' 'dvpspq' 'adjex']